name = "scratchsocket"
version = "0.2.1"
authors = [
  { name="Abhiram V", email="abhiram.tx@gmail.com" },
]
description = "Establish simple cloud connections with scratch.mit.edu!"
readme = "README.md"
license = { file="LICENSE" }
requires-python = ">=3.7"
install_requires=["websocket-client", "requests", "numpy"]
classifiers = [
    "Programming Language :: Python :: 2",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]


Homepage = "https://github.com/abhiramtx/scratchsocket"
BugTracker = "https://github.com/abhiramtx/scratchsocket/issues"